# Site settings
title: Resume
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Soma Narikiyo
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Love learning new things or tools everyday. If I do not know something I will learn it.
user_title: Software Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src' , 'node_modules']
