baseURL = "https://kiyo27.github.io/"
languageCode = "ja"
title = "kiyo27 blog"
theme = "hugo-book"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true
defaultContentLanguage = "ja"
hasCJKLanguage = true


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[security] 
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^code']